import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Picture App",
  description: "Generated by Jokeay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen">
          <div className="h-20 z-50 fixed top-0 w-full bg-white">
            <Navbar />
          </div>
          <div className="left-0 top-0 absolute w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
