import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import AuthProvider from "./components/AuthProvider";
import QueryProvider from "./components/QueryProvider";
import { useSession } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Picture App",
  description: "Generated by Jokeay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            <div className="w-full h-screen">
              <div className="h-20 z-50 fixed top-0 w-full bg-white">
                <Navbar />
              </div>
              <div className="left-0 top-0 absolute w-full">{children}</div>
            </div>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
