import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Picture App",
  description: "Generated by Jokeay",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to-green-100">
          <div className="h-20">
            <Navbar />
          </div>
          <div className="h-[calc(100vh-5rem)]">{children}</div>
        </div>
      </body>
    </html>
  );
}
